### ISSUE TITLE
Test results are to low 

### ISSUE THREAD

**Issue by sonyccd** [snakes-in-the-box/super-awesome-txt-classifier#6]
45% is way to low we need to figure out why that is like that.

**Comment by brentcl** [comment]
Anyone have any progress on increasing accuracy?

**Comment by chandlerkincaid** [comment]
Getting started on running it on my machine

**Comment by brentcl** [comment]
Issue is that in NB you need to count each category's dict as containing the global dictionary seen in training. Add 1 to every word count so that there are no 0s. Then the test target instances count as also having the entire training dict, then if seeing a word that was not there before just add it with a 1.
